In [1]:
import pandas as pd

In [4]:
#to load the data back in use
df_full = pd.read_pickle('original_turnstile_df.pkl')

In [6]:
df_full.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2020,00:00:00,REGULAR,7450785,2533372
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2020,04:00:00,REGULAR,7450788,2533375
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2020,08:00:00,REGULAR,7450798,2533391
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2020,12:00:00,REGULAR,7450826,2533423
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2020,16:00:00,REGULAR,7450910,2533454

In [7]:
#create a new column with using the date & time columns,
# then turning it into a datetime object
df_full['DateTime'] = pd.to_datetime(df_full.DATE.astype(str) + " " + df_full.TIME.astype(str))

In [11]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', None)

In [10]:
#grouping by turnstiles locations and summing entries/exits by date
# note that SCP is the only location specific column that changes
turnstiles_df = df_full.groupby(['C/A', 'UNIT', 'STATION', 'SCP', 'DATE' ]).sum()

In [12]:
turnstiles_df

                                               ENTRIES  \
C/A   UNIT STATION       SCP      DATE
A002  R051 59 ST         02-00-00 08/29/2020  44705127
                                  08/30/2020  44706856
                                  08/31/2020  44708630
                                  09/01/2020  44711777
                                  09/02/2020  44714663
...                                                ...
TRAM2 R469 RIT-ROOSEVELT 00-05-01 09/14/2020     33324
                                  09/15/2020     33324
                                  09/16/2020     33324
                                  09/17/2020     33324
                                  09/18/2020     33324

                                              EXITS
C/A   UNIT STATION       SCP      DATE
A002  R051 59 ST         02-00-00 08/29/2020                                           15200485
                                  08/30/2020                                           15201071
                                  08/31/2020                                           15201988
                                  09/01/2020                                           15203251
                                  09/02/2020                                           15204492
...                                                                                         ...
TRAM2 R469 RIT-ROOSEVELT 00-05-01 09/14/2020                                               3246
                                  09/15/2020                                               3246
                                  09/16/2020                                               3246
                                  09/17/2020                                               3246
                                  09/18/2020                                               3246

[103684 rows x 2 columns]

In [13]:
#this is a single turnstile at one location
first_turnstile = turnstiles_df.loc[lambda turnstiles_df: turnstiles_df['STATION'] == '59 ST'].loc[lambda turnstiles_df: turnstiles_df['SCP'] == '02-00-00'].loc[lambda turnstiles_df: turnstiles_df['UNIT'] == 'R051'].loc[lambda turnstiles_df: turnstiles_df['C/A'] == 'A002']

KeyError: 'STATION'